name 'bmearns'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bmearns'
long_description 'Installs/Configures bmearns'
version '0.1.0'
